# Generated by Django 4.2.5 on 2023-10-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='order_dish',
            options={'verbose_name': 'Блюдо заказа', 'verbose_name_plural': 'Блюда заказов'},
        ),
        migrations.AlterModelOptions(
            name='staffer',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='type_of_dish',
            field=models.CharField(blank=True, choices=[('first', 'первое'), ('second', 'второе'), ('drink', 'напиток'), ('dessert', 'десерт'), ('snack', 'закуска')], max_length=30, null=True),
        ),
    ]
