# Generated by Django 4.2.5 on 2023-10-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_food', '0002_alter_dish_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='type_of_dish',
            field=models.CharField(choices=[('first', 'первое'), ('second', 'второе'), ('drink', 'напиток'), ('dessert', 'десерт'), ('snack', 'закуска')], max_length=30),
        ),
    ]
