# Generated by Django 4.2.5 on 2023-10-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_food', '0003_alter_dish_calories_alter_dish_type_of_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateField(auto_now=True),
        ),
    ]
