# Generated by Django 4.2.5 on 2023-10-10 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_food', '0006_order_dishes_alter_order_date_delete_order_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporate_food.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporate_food.order')),
            ],
            options={
                'verbose_name': 'Блюдо заказа',
                'verbose_name_plural': 'Блюда заказов',
            },
        ),
    ]
